### PR TITLE
Use PlantUML Version 8054

### PR DESCRIPTION
**Pull request by rjw245**
Replace PlantUML JAR file.
Update plantuml.py to expect this new version, which presents its -version text differently.
Notable new features since 8024:
- Timing diagrams
- Running PlantUML without Graphviz/Dot dependency
- Several new integrations (TexWriting.com, Fitnesse Wiki, Docker, WordPress, etc)
- Bug fixes
- Use hyperlinks and URL in your diagrams.
- Improvements to Beta Activity Diagram
- Use Ascii Math into your diagram.

Full PlantUML release notes: http://plantuml.com/old-news

### CODE REVIEW

**Comment by jvantuyl** [comment]
Can you rebase this on the new head? Should be pretty trivial.

**Comment by rjw245** [comment]
Just rebased on origin/master.
Few things I wanted to get opinions on:
- From master, it appears you had left the old 8024 JAR in the diagram folder. Should older versions be left in the repository generally, or removed?
- There's a bit of duplication in how I am storing the versions, since I need both a build number and a date string. The date string is used in the -v flag version check code, since PlantUML now reports this instead of the build number. Let me know if you have thoughts on how to keep the two consistent more easily.

**Comment by jvantuyl** [comment]
I’m fine with removing the stale JAR. The extra info seems unavoidable, so I guess that’ll have to do.

**Comment by jvantuyl** [comment]
Well, maybe we could pass it around as a tuple? Doesn’t seem like a big win, though. As long as they both live in the same file (with maybe a clarifying comment) it’s probably good enough.

**Pull request merged**
